repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: check-merge-conflict
  - id: check-added-large-files
  - id: debug-statements
  - id: detect-aws-credentials
  - id: detect-private-key

- repo: https://github.com/asottile/reorder_python_imports
  rev: v3.12.0
  hooks:
  - id: reorder-python-imports
    args: [--py39-plus, --add-import, 'from __future__ import annotations']

- repo: https://github.com/asottile/add-trailing-comma
  rev: v3.1.0
  hooks:
  - id: add-trailing-comma

- repo: https://github.com/asottile/pyupgrade
  rev: v3.15.0
  hooks:
  - id: pyupgrade
    args: [--py311-plus, --keep-runtime-typing]
    exclude: ^install-local.py$

- repo: https://github.com/pycqa/autoflake
  rev: v2.2.1
  hooks:
  - id: autoflake
    args: [--in-place, --remove-all-unused-imports, --remove-unused-variables, --ignore-init-module-imports]
    additional_dependencies: [flake8-builtins]

- repo: https://github.com/psf/black
  rev: 23.11.0
  hooks:
  - id: black
